# Site settings
title: DALI 2019 - Data, Learning and Inference
permalink: "/:categories/:title.html"
# Include image banner file name below
banner: banner.jpg
banner_title: Image cc BY-SA 3.0

# Registration fees and URL go here.
registration:
  fee:
    academic: 450 euros
    industry: 600 euros
  url:

# Hotel booking URL goes here
booking:
  url: 
  
conference:
  draft: true
  hide_tentative: true
  hosts:
  general:
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - given: Bernhard
    family: Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon
  chair:
  scientific_coordinators:
  - given: Matthias
    family: Hohmann
    url: https://ei.is.tuebingen.mpg.de/person/mhohmann
    institute: MPI for Intelligent Systems (Tübingen)
  assistants:
  - given: Julia
    family: Braun
    url: "https://www.is.mpg.de/person/jbraun"
    institute: MPI for Intelligent Systems (Tübingen)
  - given: Maria
    family: Püschel
    institute: MPI for Intelligent Systems (Tübingen)
  steering:
  - given: Zoubin
    family: Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge and Uber
  - given: Thomas
    family: Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - given: Bernhard
    family: Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen)
  name: DALI 2019 - Data Learning and Inference
  shortname: DALI
  venue: Kursaal
  venue_url: https://www.kursaal.eus/en/
  location: San Sebastian, Spain
  year: 2019
  month: September
  dates:
  - 2019-09-03
  - 2019-09-04
  - 2019-09-05
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
github:
  edit: true
  repository: dalimeeting.github.io
future: true

# Build settings
markdown: kramdown
