# Site settings
title: DALI 2019 - Data, Learning and Inference
permalink: "/:categories/:title.html"
# Include image banner file name below
banner: george-fancourt.png

# Registration fees and URL go here.
registration:
  fee:
    academic: 450 euros
    industry: 600 euros
  url:

# Hotel booking URL goes here
booking:
  url:
  
conference:
  draft: true
  hide_tentative: true
  hosts:
  general:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon
  chair:
  - given: Arthur
    family: Gretton
    institute: "Gatsby Unit, University College London"
    url: "http://www.gatsby.ucl.ac.uk/~gretton/"
  - given: Shakir 
    family: Mohamed
    url: "https://shakirm.com/"
    institute: "Google DeepMind"
  - name: Krikamol Muandet
    url: "http://krikamol.org"
    institute: "MPI for Intelligent Systems (Tübingen)"  
  assistants:
  - name: Diana Rebmann 
    url: "https://ei.is.tuebingen.mpg.de/person/drebmann"
    institute: DeepMind
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge and Uber
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen)
  name: DALI 2019 - Data Learning and Inference
  shortname: DALI
  venue: Fancourt
  location: San Sebastian, Spain
  year: 2019
  month: September
  dates:
  - 2019-09-03
  - 2019-09-04
  - 2019-09-05
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
previous_meeting:
  name: DALI 2019
  url: "http://dalimeeting.org/dali2019/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
github:
  edit: true
  repository: dalimeeting.github.io
future: true

# Build settings
markdown: kramdown
