# Site settings
title: DALI 2017 - Data Learning and Inference
permalink: "/:categories/:title.html"
# Include image banner file name below
banner: costa-adeje.jpg 
conference:
  draft: true
  hosts:
  general:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Bernhard Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems Tübingen
  workshop:
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  symposium:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  local:
  - name: Pablo M. Olmos
    url: "http://www.tsc.uc3m.es/~olmos/"
    institute: "Universidad Carlos III de Madrid"
  - name: Isabel Valera
    url: "http://www.mpi-sws.org/~ivalera/"
    institute: "Max Planck Institute for Software Systems"
  assistants:
  - name: Sabrina Nepozitek
    url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
    institute: ETH Zurich
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2017 - Data Learning and Inference
  venue: H10 Costa Adeje Palace
  location: Tenerife, Canary Islands
  year: 2017
  month: April
  dates:
  - 2017-04-18
  - 2017-04-19
  - 2017-04-20
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
previous_meeting:
  name: DALI 2016
  url: "http://dalimeeting.org/dali2016/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
future: true

# Build settings
markdown: kramdown
