# Site settings
title: DALI 2016 - Data Learning and Inference
venue: Sestri Levante, Italy
permalink: "/:categories/:title.html"
banner: sestri.jpeg
conference:
  hosts:
  general:
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  workshop:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  symposium:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  local:
  - name: Lorenzo Rosasco
    url: "http://web.mit.edu/lrosasco/www/"
    institute: University of Genova and MIT
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2016 - Data Learning and Inference
  location: Sestri Levante, Italy
  year: 2016
  month: March
  dates:
  - 2016-03-30
  - 2016-03-31
  - 2016-04-01
  draft: True # set to True if the programme is draft only.
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting

# Build settings
markdown: kramdown
