
# Global site settings
title: DALI 2020
subtitle: Data, Learning and Inference
permalink: "/:categories/:title.html"
baseurl: ""
url: ""


# Also generate pages with dates in the future
future: true


# Additional build settings
markdown: kramdown


# Minify HTML
compress_html:
  clippings: all
  comments: all
  blanklines: true


# Include image banner file name below
banner: banner.jpg


# Conference information
conference:

  draft: false
  hide_tentative: true

  name: DALI 2020 — Data, Learning and Inference
  shortname: DALI
  venue: H10 Punta Negra Hotel
  venue_url: https://www.h10hotels.com/en/mallorca-hotels/h10-punta-negra 
  location: Costa d'en Blanes, Balearic Islands, Spain
  year: 2020
  month: October
  dates:
  - 2020-10-25
  - 2020-10-26
  - 2020-10-27
  - 2020-10-28

  sponsors:
  - name: Max Planck ETH Center for Learning Systems
    url: "https://learning-systems.org/"

  general:
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: University of Cambridge
  - given: Bernhard
    family: Schölkopf
    url: "https://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon

  local:
  - given: Gergely
    family: Neu
    url: http://cs.bme.hu/~gergo/
    institute: Universitat Pompeu Fabra
  - given: Vicenç 
    family: Gómez
    url: https://www.upf.edu/web/vgomez
    institute: Universitat Pompeu Fabra

  workshop:
  - given: Gergely
    family: Neu
    url: http://cs.bme.hu/~gergo/
    institute: Universitat Pompeu Fabra
  - given: Lorenzo 
    family: Rosasco
    url: http://web.mit.edu/lrosasco/www/
    institute: Universita' di Genova and Massachusetts Institute of Technology

  assistants:
  - given: Diana
    family: Rebmann
    institute: DeepMind (Montréal)
  - given: Timothy
    family: Gebhard
    url: "https://timothygebhard.de"
    institute: MPI for Intelligent Systems (Tübingen) and ETH Zurich

  steering:
  - given: Zoubin
    family: Ghahramani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge and Uber
  - given: Thomas
    family: Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: University of Cambridge
  - given: Bernhard
    family: Schölkopf
    url: "https://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon


# Set up collections (for workshops and schedule)
collections:
  workshops:
    output: true
    permalink: /workshops/:name
  schedule:
    output: true
    permalink: /schedule/:name

# Social media settings
contact_email: drebmann@google.com
github_username: dalimeeting
twitter_username:
